### ISSUE TITLE
Command line gpg and this java library produces different results

### ISSUE THREAD

**Issue by jaas0301** [neuhalje/bouncy-gpg#43]
How do I convert following command into the equivalent using this library.

`gpg -e -r "recipient" --output output.gpg input.zip` 

I have tried following options but with no success:

```
final OutputStream outputStream = BouncyGPG.encryptToStream()
	        .withConfig(keyring)
	        .withOxAlgorithms()
	        //.withDefaultAlgorithms()
                //.withAlgorithms(new PGPAlgorithmSuite(PGPHashAlgorithms.SHA_256 , 
                //   PGPSymmetricEncryptionAlgorithms.AES_256, 
                //   PGPCompressionAlgorithms.ZLIB))
	        .toRecipient("recipient")
	        .andDoNotSign()
	        .binaryOutput()
	        .andWriteTo(encrypted);
```

Every time I encrypt a file using command line and using the code, I get two different results. One with the command line for example if is 300KB, then the one with the code is almost twice the size  ~550KB. 

Our legacy system is having issues decrypting the gpg file coming from this java library. However, if encrypted using command line GPG GnuPG (2.17.2) version using the command, it is able to decrypt. 

Any help will be highly appreciated.

**Comment by neuhalje** [comment]
Some questions to narrow that down:
- What version of gpg is the legacy system using?
- What error do you get? Can you try to decrypt with `-vv` for a verbose output?
- The larger file size might be caused by using ZLIB vs. [BZIP2](https://github.com/neuhalje/bouncy-gpg/blob/master/src/main/java/name/neuhalfen/projects/crypto/bouncycastle/openpgp/algorithms/PGPCompressionAlgorithms.java#L31).

**Comment by jaas0301** [comment]
I had to use binaryOutput instead of armorAsciiOutput. 

This is a non issue, hence should be closed.
